site_name: Pilot Info
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - content.tabs.link
copyright: Copyright &copy; 2023 Olaf Blom | I do not claim ownership of any picture used on this website | ! NOT FOR REAL WORLD USAGE !
extra:
  generator: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - literate-nav:
      nav_file: summary.md